name: 👓 Add preview link

on: pull_request

jobs:
  comment:
    name: Add preview link to pull request
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: '👓 [Open preview on frontend.live](https://www.frontend.live/${{ github.repository }}/${{ github.head_ref }}/index.html)'
          check_for_duplicate_msg: false
