name: 🚚 Deploy to frontend.live

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: 'eu-central-1'
  AWS_S3_BUCKET: 'frontend-live-preview'

jobs:
  deploy:
    name: Deploy to frontend.live Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Cache npm dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run npm install (skipped if cache-hit exists)
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build

      - name: Move zip file
        run: zip -r dist.zip ./dist; mv dist.zip dist/
        if: github.ref == 'refs/heads/develop'

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Deploy to frontend.live
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_SECRET }}
          SOURCE_DIR: 'dist'
          DEST_DIR: '${{ github.repository }}/${BRANCH_NAME}'

      - name: Invalidate CDN cache
        uses: awact/cloudfront-action@0.1.2
        env:
          DISTRIBUTION_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DISTRIBUTION_ID }}
          SOURCE_DIR: '${{ github.repository }}/${BRANCH_NAME}'
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_LIVE_PREVIEW_DEPLOY_AWS_ACCESS_SECRET }}
